# Generated by Django 2.2.13 on 2021-01-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='电影名称')),
                ('cover', models.CharField(max_length=100, verbose_name='电影封面')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotent', models.CharField(max_length=255, verbose_name='短评内容')),
                ('star', models.SmallIntegerField(verbose_name='星级')),
                ('comment_info', models.CharField(max_length=50, verbose_name='用户名')),
                ('avatar', models.CharField(max_length=200, verbose_name='星级')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='douban.Movie')),
            ],
        ),
    ]
