# Generated by Django 2.2.13 on 2021-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cotent',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(max_length=200, verbose_name='头像'),
        ),
    ]
