# Generated by Django 2.2.13 on 2021-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0002_auto_20210130_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie_id',
            field=models.IntegerField(verbose_name='电影id'),
        ),
    ]
