# Generated by Django 2.2.13 on 2021-01-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0003_auto_20210130_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='短评内容'),
        ),
    ]
